### ISSUE TITLE
openbsd: failed to load font

### ISSUE THREAD

**Issue by afloworg** [jefbed/jbxvt#12]
I am new to OpenBSD so this could be my bad, however...

git cloned, configure, make... all good so far
on first run segfault on starting tmux, ok lets try again without tmux.

Now it just sits at
Failed to load font: -*-terminus-medium-r-*-*-14-*-*-*-*-*-iso10646-*
Failed to load font: -*-terminus-bold-r-*-*-14-*-*-*-*-*-iso10646-*

running in i3 on OpenBSD 6.4. Just ask if you want any more info.

**Comment by alisabedard** [comment]
You need to have the terminus font within your font path.  Alternatively,
you can change the default fonts used by editing config.h.  Or, you can
start jbxvt as follows:
jbxvt -B fixed -F fixed

Either way, use a valid font of your choice.
It should have loaded 'fixed' as a fallback, though--what you see are
informational warnings.  So your issue may be session related.  I have yet
to test jbxvt with the newest OpenBSD release.  It was ported to the 6.0
release.  So I suspect the issue is related to how a session is started in
the new release.
If you break execution in gdb, what is the back trace?
Regards,
Jeff Bedard

**Comment by alisabedard** [comment]
The default font is now lucidasanstypewriter, which is available by default on OpenBSD's X server installation.  tmux also started successfully in testing.
